[package]
name = "geese"
version = "0.1.12"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/geese"
readme = "README.md"
description = """
Dead-simple game event system for Rust.
"""

[dependencies]
fxhash = "0.2.1"
topological-sort = "0.2.2"